### ISSUE TITLE
Manual approval required for workflow run 9731742849

### ISSUE THREAD

**Issue by pandudw** [Gladiator-Squad/Laravel_Laracamp#3]
Workflow is pending manual review.
URL: https://api.github.com/Gladiator-Squad/Laravel_Laracamp/actions/runs/9731742849

Required approvers: [wapol4]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by Wapol4** [comment]
approved

**Comment by Wapol4** [comment]
yes

**Comment by pandudw** [comment]
Workflow cancelled, closing issue.
