### ISSUE TITLE
Manual approval required for workflow run 9741696930: Deploying v1.0.2 to prod from staging

### ISSUE THREAD

**Issue by pandudw** [Gladiator-Squad/Laravel_Laracamp#5]
Please approve or deny the deployment of version v1.0.2.

Workflow is pending manual review.
URL: https://api.github.com/Gladiator-Squad/Laravel_Laracamp/actions/runs/9741696930

Required approvers: [pandudw wapol4]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by Wapol4** [comment]
approved

**Comment by Wapol4** [comment]
approve

**Comment by pandudw** [comment]
Workflow cancelled, closing issue.
