### ISSUE TITLE
Manual approval required for workflow run 9756141990: Deploying  to prod from staging

### ISSUE THREAD

**Issue by pandudw** [Gladiator-Squad/Laravel_Laracamp#6]
Please approve or deny the deployment of version .

Workflow is pending manual review.
URL: https://api.github.com/Gladiator-Squad/Laravel_Laracamp/actions/runs/9756141990

Required approvers: [pandudw wapol4]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by Wapol4** [comment]
Approved

**Comment by Wapol4** [comment]
approved

**Comment by pandudw** [comment]
Workflow cancelled, closing issue.
